/**
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Stories</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STORIES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.UserStoryImpl <em>User Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.UserStoryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getUserStory()
   * @generated
   */
  int USER_STORY = 1;

  /**
   * The feature id for the '<em><b>Titel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY__TITEL = 0;

  /**
   * The feature id for the '<em><b>Rolle</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY__ROLLE = 1;

  /**
   * The feature id for the '<em><b>Ziel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY__ZIEL = 2;

  /**
   * The feature id for the '<em><b>Nutzen</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY__NUTZEN = 3;

  /**
   * The number of structural features of the '<em>User Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TitelImpl <em>Titel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TitelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTitel()
   * @generated
   */
  int TITEL = 2;

  /**
   * The feature id for the '<em><b>Subjekt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL__SUBJEKT = 0;

  /**
   * The feature id for the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL__VERB = 1;

  /**
   * The number of structural features of the '<em>Titel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RolleImpl <em>Rolle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RolleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRolle()
   * @generated
   */
  int ROLLE = 3;

  /**
   * The feature id for the '<em><b>Subjekt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE__SUBJEKT = 0;

  /**
   * The number of structural features of the '<em>Rolle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl <em>Ziel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ZielImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getZiel()
   * @generated
   */
  int ZIEL = 4;

  /**
   * The feature id for the '<em><b>Lchars</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__LCHARS = 0;

  /**
   * The feature id for the '<em><b>Subjekt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__SUBJEKT = 1;

  /**
   * The feature id for the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__VERB = 2;

  /**
   * The number of structural features of the '<em>Ziel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NutzenImpl <em>Nutzen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NutzenImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNutzen()
   * @generated
   */
  int NUTZEN = 5;

  /**
   * The feature id for the '<em><b>Subjekt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__SUBJEKT = 0;

  /**
   * The feature id for the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__VERB = 1;

  /**
   * The number of structural features of the '<em>Nutzen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getStories <em>Stories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stories</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getStories()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Stories();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.UserStory <em>User Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Story</em>'.
   * @see org.xtext.example.mydsl.myDsl.UserStory
   * @generated
   */
  EClass getUserStory();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.UserStory#getTitel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Titel</em>'.
   * @see org.xtext.example.mydsl.myDsl.UserStory#getTitel()
   * @see #getUserStory()
   * @generated
   */
  EReference getUserStory_Titel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.UserStory#getRolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rolle</em>'.
   * @see org.xtext.example.mydsl.myDsl.UserStory#getRolle()
   * @see #getUserStory()
   * @generated
   */
  EReference getUserStory_Rolle();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.UserStory#getZiel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ziel</em>'.
   * @see org.xtext.example.mydsl.myDsl.UserStory#getZiel()
   * @see #getUserStory()
   * @generated
   */
  EReference getUserStory_Ziel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.UserStory#getNutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.UserStory#getNutzen()
   * @see #getUserStory()
   * @generated
   */
  EReference getUserStory_Nutzen();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Titel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Titel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel
   * @generated
   */
  EClass getTitel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Titel#getSubjekt <em>Subjekt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Subjekt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel#getSubjekt()
   * @see #getTitel()
   * @generated
   */
  EAttribute getTitel_Subjekt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Titel#getVerb <em>Verb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Verb</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel#getVerb()
   * @see #getTitel()
   * @generated
   */
  EAttribute getTitel_Verb();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rolle</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rolle
   * @generated
   */
  EClass getRolle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Rolle#getSubjekt <em>Subjekt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Subjekt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rolle#getSubjekt()
   * @see #getRolle()
   * @generated
   */
  EAttribute getRolle_Subjekt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Ziel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ziel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel
   * @generated
   */
  EClass getZiel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ziel#getLchars <em>Lchars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lchars</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel#getLchars()
   * @see #getZiel()
   * @generated
   */
  EAttribute getZiel_Lchars();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ziel#getSubjekt <em>Subjekt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Subjekt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel#getSubjekt()
   * @see #getZiel()
   * @generated
   */
  EAttribute getZiel_Subjekt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ziel#getVerb <em>Verb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Verb</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel#getVerb()
   * @see #getZiel()
   * @generated
   */
  EAttribute getZiel_Verb();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Nutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen
   * @generated
   */
  EClass getNutzen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Nutzen#getSubjekt <em>Subjekt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Subjekt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen#getSubjekt()
   * @see #getNutzen()
   * @generated
   */
  EAttribute getNutzen_Subjekt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Nutzen#getVerb <em>Verb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Verb</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen#getVerb()
   * @see #getNutzen()
   * @generated
   */
  EAttribute getNutzen_Verb();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Stories</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STORIES = eINSTANCE.getModel_Stories();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.UserStoryImpl <em>User Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.UserStoryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getUserStory()
     * @generated
     */
    EClass USER_STORY = eINSTANCE.getUserStory();

    /**
     * The meta object literal for the '<em><b>Titel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY__TITEL = eINSTANCE.getUserStory_Titel();

    /**
     * The meta object literal for the '<em><b>Rolle</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY__ROLLE = eINSTANCE.getUserStory_Rolle();

    /**
     * The meta object literal for the '<em><b>Ziel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY__ZIEL = eINSTANCE.getUserStory_Ziel();

    /**
     * The meta object literal for the '<em><b>Nutzen</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY__NUTZEN = eINSTANCE.getUserStory_Nutzen();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TitelImpl <em>Titel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TitelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTitel()
     * @generated
     */
    EClass TITEL = eINSTANCE.getTitel();

    /**
     * The meta object literal for the '<em><b>Subjekt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITEL__SUBJEKT = eINSTANCE.getTitel_Subjekt();

    /**
     * The meta object literal for the '<em><b>Verb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITEL__VERB = eINSTANCE.getTitel_Verb();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RolleImpl <em>Rolle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RolleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRolle()
     * @generated
     */
    EClass ROLLE = eINSTANCE.getRolle();

    /**
     * The meta object literal for the '<em><b>Subjekt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLLE__SUBJEKT = eINSTANCE.getRolle_Subjekt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl <em>Ziel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ZielImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getZiel()
     * @generated
     */
    EClass ZIEL = eINSTANCE.getZiel();

    /**
     * The meta object literal for the '<em><b>Lchars</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZIEL__LCHARS = eINSTANCE.getZiel_Lchars();

    /**
     * The meta object literal for the '<em><b>Subjekt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZIEL__SUBJEKT = eINSTANCE.getZiel_Subjekt();

    /**
     * The meta object literal for the '<em><b>Verb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZIEL__VERB = eINSTANCE.getZiel_Verb();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NutzenImpl <em>Nutzen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NutzenImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNutzen()
     * @generated
     */
    EClass NUTZEN = eINSTANCE.getNutzen();

    /**
     * The meta object literal for the '<em><b>Subjekt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTZEN__SUBJEKT = eINSTANCE.getNutzen_Subjekt();

    /**
     * The meta object literal for the '<em><b>Verb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTZEN__VERB = eINSTANCE.getNutzen_Verb();

  }

} //MyDslPackage
