/**
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Titel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Titel#getSubjekt <em>Subjekt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Titel#getVerb <em>Verb</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel()
 * @model
 * @generated
 */
public interface Titel extends EObject
{
  /**
   * Returns the value of the '<em><b>Subjekt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subjekt</em>' attribute.
   * @see #setSubjekt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel_Subjekt()
   * @model
   * @generated
   */
  String getSubjekt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Titel#getSubjekt <em>Subjekt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subjekt</em>' attribute.
   * @see #getSubjekt()
   * @generated
   */
  void setSubjekt(String value);

  /**
   * Returns the value of the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verb</em>' attribute.
   * @see #setVerb(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel_Verb()
   * @model
   * @generated
   */
  String getVerb();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Titel#getVerb <em>Verb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verb</em>' attribute.
   * @see #getVerb()
   * @generated
   */
  void setVerb(String value);

} // Titel
