/**
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Story</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UserStory#getTitel <em>Titel</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UserStory#getRolle <em>Rolle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UserStory#getZiel <em>Ziel</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UserStory#getNutzen <em>Nutzen</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUserStory()
 * @model
 * @generated
 */
public interface UserStory extends EObject
{
  /**
   * Returns the value of the '<em><b>Titel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titel</em>' containment reference.
   * @see #setTitel(Titel)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUserStory_Titel()
   * @model containment="true"
   * @generated
   */
  Titel getTitel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UserStory#getTitel <em>Titel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titel</em>' containment reference.
   * @see #getTitel()
   * @generated
   */
  void setTitel(Titel value);

  /**
   * Returns the value of the '<em><b>Rolle</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rolle</em>' containment reference.
   * @see #setRolle(Rolle)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUserStory_Rolle()
   * @model containment="true"
   * @generated
   */
  Rolle getRolle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UserStory#getRolle <em>Rolle</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rolle</em>' containment reference.
   * @see #getRolle()
   * @generated
   */
  void setRolle(Rolle value);

  /**
   * Returns the value of the '<em><b>Ziel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ziel</em>' containment reference.
   * @see #setZiel(Ziel)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUserStory_Ziel()
   * @model containment="true"
   * @generated
   */
  Ziel getZiel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UserStory#getZiel <em>Ziel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ziel</em>' containment reference.
   * @see #getZiel()
   * @generated
   */
  void setZiel(Ziel value);

  /**
   * Returns the value of the '<em><b>Nutzen</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nutzen</em>' containment reference.
   * @see #setNutzen(Nutzen)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUserStory_Nutzen()
   * @model containment="true"
   * @generated
   */
  Nutzen getNutzen();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UserStory#getNutzen <em>Nutzen</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nutzen</em>' containment reference.
   * @see #getNutzen()
   * @generated
   */
  void setNutzen(Nutzen value);

} // UserStory
