/*
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.myDsl.Model;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Nutzen;
import org.xtext.example.mydsl.myDsl.Rolle;
import org.xtext.example.mydsl.myDsl.Titel;
import org.xtext.example.mydsl.myDsl.UserStory;
import org.xtext.example.mydsl.myDsl.Ziel;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case MyDslPackage.NUTZEN:
				sequence_Nutzen(context, (Nutzen) semanticObject); 
				return; 
			case MyDslPackage.ROLLE:
				sequence_Rolle(context, (Rolle) semanticObject); 
				return; 
			case MyDslPackage.TITEL:
				sequence_Titel(context, (Titel) semanticObject); 
				return; 
			case MyDslPackage.USER_STORY:
				sequence_UserStory(context, (UserStory) semanticObject); 
				return; 
			case MyDslPackage.ZIEL:
				sequence_Ziel(context, (Ziel) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     stories+=UserStory+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Nutzen returns Nutzen
	 *
	 * Constraint:
	 *     (subjekt=SUBSTANTIV verb=INF_ZU_VERB)
	 * </pre>
	 */
	protected void sequence_Nutzen(ISerializationContext context, Nutzen semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.NUTZEN__SUBJEKT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.NUTZEN__SUBJEKT));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.NUTZEN__VERB) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.NUTZEN__VERB));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNutzenAccess().getSubjektSUBSTANTIVTerminalRuleCall_0_0(), semanticObject.getSubjekt());
		feeder.accept(grammarAccess.getNutzenAccess().getVerbINF_ZU_VERBTerminalRuleCall_1_0(), semanticObject.getVerb());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rolle returns Rolle
	 *
	 * Constraint:
	 *     subjekt=SUBSTANTIV
	 * </pre>
	 */
	protected void sequence_Rolle(ISerializationContext context, Rolle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ROLLE__SUBJEKT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ROLLE__SUBJEKT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRolleAccess().getSubjektSUBSTANTIVTerminalRuleCall_0(), semanticObject.getSubjekt());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Titel returns Titel
	 *
	 * Constraint:
	 *     (subjekt=SUBSTANTIV verb=INF_VERB)
	 * </pre>
	 */
	protected void sequence_Titel(ISerializationContext context, Titel semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.TITEL__SUBJEKT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.TITEL__SUBJEKT));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.TITEL__VERB) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.TITEL__VERB));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTitelAccess().getSubjektSUBSTANTIVTerminalRuleCall_0_0(), semanticObject.getSubjekt());
		feeder.accept(grammarAccess.getTitelAccess().getVerbINF_VERBTerminalRuleCall_1_0(), semanticObject.getVerb());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UserStory returns UserStory
	 *
	 * Constraint:
	 *     (titel=Titel rolle=Rolle ziel=Ziel nutzen=Nutzen)
	 * </pre>
	 */
	protected void sequence_UserStory(ISerializationContext context, UserStory semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.USER_STORY__TITEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.USER_STORY__TITEL));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.USER_STORY__ROLLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.USER_STORY__ROLLE));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.USER_STORY__ZIEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.USER_STORY__ZIEL));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.USER_STORY__NUTZEN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.USER_STORY__NUTZEN));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUserStoryAccess().getTitelTitelParserRuleCall_0_0(), semanticObject.getTitel());
		feeder.accept(grammarAccess.getUserStoryAccess().getRolleRolleParserRuleCall_3_0(), semanticObject.getRolle());
		feeder.accept(grammarAccess.getUserStoryAccess().getZielZielParserRuleCall_6_0(), semanticObject.getZiel());
		feeder.accept(grammarAccess.getUserStoryAccess().getNutzenNutzenParserRuleCall_9_0(), semanticObject.getNutzen());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Ziel returns Ziel
	 *
	 * Constraint:
	 *     (lchars=LOWER_SEQ? subjekt=SUBSTANTIV verb=INF_VERB)
	 * </pre>
	 */
	protected void sequence_Ziel(ISerializationContext context, Ziel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
