/*
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Model");
		private final Assignment cStoriesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStoriesUserStoryParserRuleCall_0 = (RuleCall)cStoriesAssignment.eContents().get(0);
		
		//Model:
		//    stories+=UserStory*;
		@Override public ParserRule getRule() { return rule; }
		
		//stories+=UserStory*
		public Assignment getStoriesAssignment() { return cStoriesAssignment; }
		
		//UserStory
		public RuleCall getStoriesUserStoryParserRuleCall_0() { return cStoriesUserStoryParserRuleCall_0; }
	}
	public class UserStoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.UserStory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitelTitelParserRuleCall_0_0 = (RuleCall)cTitelAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAlsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRolleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRolleRolleParserRuleCall_3_0 = (RuleCall)cRolleAssignment_3.eContents().get(0);
		private final Keyword cMöchteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cIchKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cZielAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cZielZielParserRuleCall_6_0 = (RuleCall)cZielAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cUmKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cNutzenAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cNutzenNutzenParserRuleCall_9_0 = (RuleCall)cNutzenAssignment_9.eContents().get(0);
		private final Keyword cFullStopKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//UserStory:
		//    titel=Titel ':' 'Als' rolle=Rolle 'möchte' 'ich' ziel=Ziel ',' 'um' nutzen=Nutzen '.';
		@Override public ParserRule getRule() { return rule; }
		
		//titel=Titel ':' 'Als' rolle=Rolle 'möchte' 'ich' ziel=Ziel ',' 'um' nutzen=Nutzen '.'
		public Group getGroup() { return cGroup; }
		
		//titel=Titel
		public Assignment getTitelAssignment_0() { return cTitelAssignment_0; }
		
		//Titel
		public RuleCall getTitelTitelParserRuleCall_0_0() { return cTitelTitelParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//'Als'
		public Keyword getAlsKeyword_2() { return cAlsKeyword_2; }
		
		//rolle=Rolle
		public Assignment getRolleAssignment_3() { return cRolleAssignment_3; }
		
		//Rolle
		public RuleCall getRolleRolleParserRuleCall_3_0() { return cRolleRolleParserRuleCall_3_0; }
		
		//'möchte'
		public Keyword getMöchteKeyword_4() { return cMöchteKeyword_4; }
		
		//'ich'
		public Keyword getIchKeyword_5() { return cIchKeyword_5; }
		
		//ziel=Ziel
		public Assignment getZielAssignment_6() { return cZielAssignment_6; }
		
		//Ziel
		public RuleCall getZielZielParserRuleCall_6_0() { return cZielZielParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//'um'
		public Keyword getUmKeyword_8() { return cUmKeyword_8; }
		
		//nutzen=Nutzen
		public Assignment getNutzenAssignment_9() { return cNutzenAssignment_9; }
		
		//Nutzen
		public RuleCall getNutzenNutzenParserRuleCall_9_0() { return cNutzenNutzenParserRuleCall_9_0; }
		
		//'.'
		public Keyword getFullStopKeyword_10() { return cFullStopKeyword_10; }
	}
	public class TitelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Titel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubjektAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubjektSUBSTANTIVTerminalRuleCall_0_0 = (RuleCall)cSubjektAssignment_0.eContents().get(0);
		private final Assignment cVerbAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVerbINF_VERBTerminalRuleCall_1_0 = (RuleCall)cVerbAssignment_1.eContents().get(0);
		
		//Titel:
		//    subjekt=SUBSTANTIV verb=INF_VERB;
		@Override public ParserRule getRule() { return rule; }
		
		//subjekt=SUBSTANTIV verb=INF_VERB
		public Group getGroup() { return cGroup; }
		
		//subjekt=SUBSTANTIV
		public Assignment getSubjektAssignment_0() { return cSubjektAssignment_0; }
		
		//SUBSTANTIV
		public RuleCall getSubjektSUBSTANTIVTerminalRuleCall_0_0() { return cSubjektSUBSTANTIVTerminalRuleCall_0_0; }
		
		//verb=INF_VERB
		public Assignment getVerbAssignment_1() { return cVerbAssignment_1; }
		
		//INF_VERB
		public RuleCall getVerbINF_VERBTerminalRuleCall_1_0() { return cVerbINF_VERBTerminalRuleCall_1_0; }
	}
	public class RolleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Rolle");
		private final Assignment cSubjektAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSubjektSUBSTANTIVTerminalRuleCall_0 = (RuleCall)cSubjektAssignment.eContents().get(0);
		
		//Rolle:
		//    subjekt=SUBSTANTIV;
		@Override public ParserRule getRule() { return rule; }
		
		//subjekt=SUBSTANTIV
		public Assignment getSubjektAssignment() { return cSubjektAssignment; }
		
		//SUBSTANTIV
		public RuleCall getSubjektSUBSTANTIVTerminalRuleCall_0() { return cSubjektSUBSTANTIVTerminalRuleCall_0; }
	}
	public class ZielElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Ziel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLcharsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLcharsLOWER_SEQTerminalRuleCall_0_0 = (RuleCall)cLcharsAssignment_0.eContents().get(0);
		private final Assignment cSubjektAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSubjektSUBSTANTIVTerminalRuleCall_1_0 = (RuleCall)cSubjektAssignment_1.eContents().get(0);
		private final Assignment cVerbAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVerbINF_VERBTerminalRuleCall_2_0 = (RuleCall)cVerbAssignment_2.eContents().get(0);
		
		//Ziel:
		//    lchars=LOWER_SEQ? subjekt=SUBSTANTIV verb=INF_VERB;
		@Override public ParserRule getRule() { return rule; }
		
		//lchars=LOWER_SEQ? subjekt=SUBSTANTIV verb=INF_VERB
		public Group getGroup() { return cGroup; }
		
		//lchars=LOWER_SEQ?
		public Assignment getLcharsAssignment_0() { return cLcharsAssignment_0; }
		
		//LOWER_SEQ
		public RuleCall getLcharsLOWER_SEQTerminalRuleCall_0_0() { return cLcharsLOWER_SEQTerminalRuleCall_0_0; }
		
		//subjekt=SUBSTANTIV
		public Assignment getSubjektAssignment_1() { return cSubjektAssignment_1; }
		
		//SUBSTANTIV
		public RuleCall getSubjektSUBSTANTIVTerminalRuleCall_1_0() { return cSubjektSUBSTANTIVTerminalRuleCall_1_0; }
		
		//verb=INF_VERB
		public Assignment getVerbAssignment_2() { return cVerbAssignment_2; }
		
		//INF_VERB
		public RuleCall getVerbINF_VERBTerminalRuleCall_2_0() { return cVerbINF_VERBTerminalRuleCall_2_0; }
	}
	public class NutzenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Nutzen");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubjektAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubjektSUBSTANTIVTerminalRuleCall_0_0 = (RuleCall)cSubjektAssignment_0.eContents().get(0);
		private final Assignment cVerbAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVerbINF_ZU_VERBTerminalRuleCall_1_0 = (RuleCall)cVerbAssignment_1.eContents().get(0);
		
		//Nutzen:
		//    subjekt=SUBSTANTIV verb=INF_ZU_VERB;
		@Override public ParserRule getRule() { return rule; }
		
		//subjekt=SUBSTANTIV verb=INF_ZU_VERB
		public Group getGroup() { return cGroup; }
		
		//subjekt=SUBSTANTIV
		public Assignment getSubjektAssignment_0() { return cSubjektAssignment_0; }
		
		//SUBSTANTIV
		public RuleCall getSubjektSUBSTANTIVTerminalRuleCall_0_0() { return cSubjektSUBSTANTIVTerminalRuleCall_0_0; }
		
		//verb=INF_ZU_VERB
		public Assignment getVerbAssignment_1() { return cVerbAssignment_1; }
		
		//INF_ZU_VERB
		public RuleCall getVerbINF_ZU_VERBTerminalRuleCall_1_0() { return cVerbINF_ZU_VERBTerminalRuleCall_1_0; }
	}
	
	
	private final ModelElements pModel;
	private final UserStoryElements pUserStory;
	private final TitelElements pTitel;
	private final RolleElements pRolle;
	private final ZielElements pZiel;
	private final NutzenElements pNutzen;
	private final TerminalRule tLOWER;
	private final TerminalRule tLOWER_NO_Z;
	private final TerminalRule tLOWER_NO_ZU;
	private final TerminalRule tINF_ZU_VERB;
	private final TerminalRule tINF_VERB;
	private final TerminalRule tSUBSTANTIV;
	private final TerminalRule tGERMAN_VERBS_ENDING;
	private final TerminalRule tLOWER_SEQ;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pUserStory = new UserStoryElements();
		this.pTitel = new TitelElements();
		this.pRolle = new RolleElements();
		this.pZiel = new ZielElements();
		this.pNutzen = new NutzenElements();
		this.tLOWER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LOWER");
		this.tLOWER_NO_Z = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LOWER_NO_Z");
		this.tLOWER_NO_ZU = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LOWER_NO_ZU");
		this.tINF_ZU_VERB = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.INF_ZU_VERB");
		this.tINF_VERB = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.INF_VERB");
		this.tSUBSTANTIV = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SUBSTANTIV");
		this.tGERMAN_VERBS_ENDING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.GERMAN_VERBS_ENDING");
		this.tLOWER_SEQ = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LOWER_SEQ");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    stories+=UserStory*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//UserStory:
	//    titel=Titel ':' 'Als' rolle=Rolle 'möchte' 'ich' ziel=Ziel ',' 'um' nutzen=Nutzen '.';
	public UserStoryElements getUserStoryAccess() {
		return pUserStory;
	}
	
	public ParserRule getUserStoryRule() {
		return getUserStoryAccess().getRule();
	}
	
	//Titel:
	//    subjekt=SUBSTANTIV verb=INF_VERB;
	public TitelElements getTitelAccess() {
		return pTitel;
	}
	
	public ParserRule getTitelRule() {
		return getTitelAccess().getRule();
	}
	
	//Rolle:
	//    subjekt=SUBSTANTIV;
	public RolleElements getRolleAccess() {
		return pRolle;
	}
	
	public ParserRule getRolleRule() {
		return getRolleAccess().getRule();
	}
	
	//Ziel:
	//    lchars=LOWER_SEQ? subjekt=SUBSTANTIV verb=INF_VERB;
	public ZielElements getZielAccess() {
		return pZiel;
	}
	
	public ParserRule getZielRule() {
		return getZielAccess().getRule();
	}
	
	//Nutzen:
	//    subjekt=SUBSTANTIV verb=INF_ZU_VERB;
	public NutzenElements getNutzenAccess() {
		return pNutzen;
	}
	
	public ParserRule getNutzenRule() {
		return getNutzenAccess().getRule();
	}
	
	//// --------------------
	//// Fragment-Terminals (nur Bausteine für Lexer)
	//// werden zum "Zusammenbauen" von Terminals verwendet
	//// --------------------
	//terminal fragment LOWER: 'a'..'z' | 'ä' | 'ö' | 'ü';
	public TerminalRule getLOWERRule() {
		return tLOWER;
	}
	
	//terminal fragment LOWER_NO_Z: 'a'..'y' | 'ä' | 'ö' | 'ü';
	public TerminalRule getLOWER_NO_ZRule() {
		return tLOWER_NO_Z;
	}
	
	//terminal fragment LOWER_NO_ZU: LOWER_NO_Z | 'z' !'u';
	public TerminalRule getLOWER_NO_ZURule() {
		return tLOWER_NO_ZU;
	}
	
	//// --------------------
	//// Terminals
	//// --------------------
	//terminal INF_ZU_VERB:
	//    LOWER_NO_ZU* 'zuzu' LOWER_NO_ZU* GERMAN_VERBS_ENDING;
	public TerminalRule getINF_ZU_VERBRule() {
		return tINF_ZU_VERB;
	}
	
	//terminal INF_VERB:
	//    LOWER+ GERMAN_VERBS_ENDING;
	public TerminalRule getINF_VERBRule() {
		return tINF_VERB;
	}
	
	//terminal SUBSTANTIV:
	//    ('A'..'Z' | 'Ä' | 'Ö' | 'Ü' ) ('a'..'z' | 'ä' | 'ö' | 'ü')*;
	public TerminalRule getSUBSTANTIVRule() {
		return tSUBSTANTIV;
	}
	
	//terminal GERMAN_VERBS_ENDING:
	//    'en' | 'ern' | 'eln';
	public TerminalRule getGERMAN_VERBS_ENDINGRule() {
		return tGERMAN_VERBS_ENDING;
	}
	
	//terminal LOWER_SEQ:
	//    LOWER+;
	public TerminalRule getLOWER_SEQRule() {
		return tLOWER_SEQ;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
