/**
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterators;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.UserStory;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  private int i = 0;

  private String content;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Iterable<UserStory> _iterable = IteratorExtensions.<UserStory>toIterable(Iterators.<UserStory>filter(resource.getAllContents(), UserStory.class));
      boolean _hasElements = false;
      for(final UserStory userstory : _iterable) {
        if (!_hasElements) {
          _hasElements = true;
          _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<userstories>\n");
        } else {
          _builder.appendImmediate("\n", "");
        }
        _builder.append("<userstory id=\"");
        int _plusPlus = this.i++;
        _builder.append(_plusPlus);
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("<titel>");
        String _subjekt = userstory.getTitel().getSubjekt();
        String _plus = (_subjekt + " ");
        String _verb = userstory.getTitel().getVerb();
        String _plus_1 = (_plus + _verb);
        _builder.append(_plus_1);
        _builder.append("</titel>");
        _builder.newLineIfNotEmpty();
        _builder.append("<rolle>");
        String _subjekt_1 = userstory.getRolle().getSubjekt();
        _builder.append(_subjekt_1);
        _builder.append("</rolle>");
        _builder.newLineIfNotEmpty();
        {
          String _lchars = userstory.getZiel().getLchars();
          boolean _tripleEquals = (_lchars == null);
          if (_tripleEquals) {
            _builder.append("<ziel>");
            String _subjekt_2 = userstory.getZiel().getSubjekt();
            String _plus_2 = (_subjekt_2 + " ");
            String _verb_1 = userstory.getZiel().getVerb();
            String _plus_3 = (_plus_2 + _verb_1);
            _builder.append(_plus_3);
            _builder.append("</ziel>");
            _builder.newLineIfNotEmpty();
          } else {
            _builder.append("<ziel>");
            String _lchars_1 = userstory.getZiel().getLchars();
            String _plus_4 = (_lchars_1 + " ");
            String _subjekt_3 = userstory.getZiel().getSubjekt();
            String _plus_5 = (_plus_4 + _subjekt_3);
            String _plus_6 = (_plus_5 + " ");
            String _verb_2 = userstory.getZiel().getVerb();
            String _plus_7 = (_plus_6 + _verb_2);
            _builder.append(_plus_7);
            _builder.append("</ziel>");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("<nutzen>");
        String _subjekt_4 = userstory.getNutzen().getSubjekt();
        String _plus_8 = (_subjekt_4 + " ");
        String _replaceFirst = userstory.getNutzen().getVerb().replaceFirst("zu", "");
        String _plus_9 = (_plus_8 + _replaceFirst);
        _builder.append(_plus_9);
        _builder.append("</nutzen>");
        _builder.newLineIfNotEmpty();
        _builder.append("</userstory>");
        _builder.newLine();
      }
      if (_hasElements) {
        _builder.append("</userstories>");
      }
    }
    this.content = _builder.toString();
    fsa.generateFile("s91127s91187.xml", this.content);
  }
}
