/*
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUserStoryAccess().getGroup(), "rule__UserStory__Group__0");
			builder.put(grammarAccess.getTitelAccess().getGroup(), "rule__Titel__Group__0");
			builder.put(grammarAccess.getZielAccess().getGroup(), "rule__Ziel__Group__0");
			builder.put(grammarAccess.getNutzenAccess().getGroup(), "rule__Nutzen__Group__0");
			builder.put(grammarAccess.getModelAccess().getStoriesAssignment(), "rule__Model__StoriesAssignment");
			builder.put(grammarAccess.getUserStoryAccess().getTitelAssignment_0(), "rule__UserStory__TitelAssignment_0");
			builder.put(grammarAccess.getUserStoryAccess().getRolleAssignment_3(), "rule__UserStory__RolleAssignment_3");
			builder.put(grammarAccess.getUserStoryAccess().getZielAssignment_6(), "rule__UserStory__ZielAssignment_6");
			builder.put(grammarAccess.getUserStoryAccess().getNutzenAssignment_9(), "rule__UserStory__NutzenAssignment_9");
			builder.put(grammarAccess.getTitelAccess().getSubjektAssignment_0(), "rule__Titel__SubjektAssignment_0");
			builder.put(grammarAccess.getTitelAccess().getVerbAssignment_1(), "rule__Titel__VerbAssignment_1");
			builder.put(grammarAccess.getRolleAccess().getSubjektAssignment(), "rule__Rolle__SubjektAssignment");
			builder.put(grammarAccess.getZielAccess().getLcharsAssignment_0(), "rule__Ziel__LcharsAssignment_0");
			builder.put(grammarAccess.getZielAccess().getSubjektAssignment_1(), "rule__Ziel__SubjektAssignment_1");
			builder.put(grammarAccess.getZielAccess().getVerbAssignment_2(), "rule__Ziel__VerbAssignment_2");
			builder.put(grammarAccess.getNutzenAccess().getSubjektAssignment_0(), "rule__Nutzen__SubjektAssignment_0");
			builder.put(grammarAccess.getNutzenAccess().getVerbAssignment_1(), "rule__Nutzen__VerbAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
