/*
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s91127s91187.ui.internal.S91127s91187Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(S91127s91187Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		S91127s91187Activator activator = S91127s91187Activator.getInstance();
		return activator != null ? activator.getInjector(S91127s91187Activator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
