/*
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s91127s91187.ui.internal.S91127s91187Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S91127s91187Activator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
