/**
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Nutzen;
import org.xtext.example.mydsl.myDsl.Rolle;
import org.xtext.example.mydsl.myDsl.Titel;
import org.xtext.example.mydsl.myDsl.UserStory;
import org.xtext.example.mydsl.myDsl.Ziel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>User Story</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserStoryImpl#getTitel <em>Titel</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserStoryImpl#getRolle <em>Rolle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserStoryImpl#getZiel <em>Ziel</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserStoryImpl#getNutzen <em>Nutzen</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UserStoryImpl extends MinimalEObjectImpl.Container implements UserStory
{
  /**
   * The cached value of the '{@link #getTitel() <em>Titel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitel()
   * @generated
   * @ordered
   */
  protected Titel titel;

  /**
   * The cached value of the '{@link #getRolle() <em>Rolle</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRolle()
   * @generated
   * @ordered
   */
  protected Rolle rolle;

  /**
   * The cached value of the '{@link #getZiel() <em>Ziel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZiel()
   * @generated
   * @ordered
   */
  protected Ziel ziel;

  /**
   * The cached value of the '{@link #getNutzen() <em>Nutzen</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNutzen()
   * @generated
   * @ordered
   */
  protected Nutzen nutzen;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UserStoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.USER_STORY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Titel getTitel()
  {
    return titel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTitel(Titel newTitel, NotificationChain msgs)
  {
    Titel oldTitel = titel;
    titel = newTitel;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__TITEL, oldTitel, newTitel);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitel(Titel newTitel)
  {
    if (newTitel != titel)
    {
      NotificationChain msgs = null;
      if (titel != null)
        msgs = ((InternalEObject)titel).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__TITEL, null, msgs);
      if (newTitel != null)
        msgs = ((InternalEObject)newTitel).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__TITEL, null, msgs);
      msgs = basicSetTitel(newTitel, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__TITEL, newTitel, newTitel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rolle getRolle()
  {
    return rolle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRolle(Rolle newRolle, NotificationChain msgs)
  {
    Rolle oldRolle = rolle;
    rolle = newRolle;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__ROLLE, oldRolle, newRolle);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRolle(Rolle newRolle)
  {
    if (newRolle != rolle)
    {
      NotificationChain msgs = null;
      if (rolle != null)
        msgs = ((InternalEObject)rolle).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__ROLLE, null, msgs);
      if (newRolle != null)
        msgs = ((InternalEObject)newRolle).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__ROLLE, null, msgs);
      msgs = basicSetRolle(newRolle, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__ROLLE, newRolle, newRolle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ziel getZiel()
  {
    return ziel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetZiel(Ziel newZiel, NotificationChain msgs)
  {
    Ziel oldZiel = ziel;
    ziel = newZiel;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__ZIEL, oldZiel, newZiel);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZiel(Ziel newZiel)
  {
    if (newZiel != ziel)
    {
      NotificationChain msgs = null;
      if (ziel != null)
        msgs = ((InternalEObject)ziel).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__ZIEL, null, msgs);
      if (newZiel != null)
        msgs = ((InternalEObject)newZiel).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__ZIEL, null, msgs);
      msgs = basicSetZiel(newZiel, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__ZIEL, newZiel, newZiel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nutzen getNutzen()
  {
    return nutzen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNutzen(Nutzen newNutzen, NotificationChain msgs)
  {
    Nutzen oldNutzen = nutzen;
    nutzen = newNutzen;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__NUTZEN, oldNutzen, newNutzen);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNutzen(Nutzen newNutzen)
  {
    if (newNutzen != nutzen)
    {
      NotificationChain msgs = null;
      if (nutzen != null)
        msgs = ((InternalEObject)nutzen).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__NUTZEN, null, msgs);
      if (newNutzen != null)
        msgs = ((InternalEObject)newNutzen).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_STORY__NUTZEN, null, msgs);
      msgs = basicSetNutzen(newNutzen, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_STORY__NUTZEN, newNutzen, newNutzen));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_STORY__TITEL:
        return basicSetTitel(null, msgs);
      case MyDslPackage.USER_STORY__ROLLE:
        return basicSetRolle(null, msgs);
      case MyDslPackage.USER_STORY__ZIEL:
        return basicSetZiel(null, msgs);
      case MyDslPackage.USER_STORY__NUTZEN:
        return basicSetNutzen(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_STORY__TITEL:
        return getTitel();
      case MyDslPackage.USER_STORY__ROLLE:
        return getRolle();
      case MyDslPackage.USER_STORY__ZIEL:
        return getZiel();
      case MyDslPackage.USER_STORY__NUTZEN:
        return getNutzen();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_STORY__TITEL:
        setTitel((Titel)newValue);
        return;
      case MyDslPackage.USER_STORY__ROLLE:
        setRolle((Rolle)newValue);
        return;
      case MyDslPackage.USER_STORY__ZIEL:
        setZiel((Ziel)newValue);
        return;
      case MyDslPackage.USER_STORY__NUTZEN:
        setNutzen((Nutzen)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_STORY__TITEL:
        setTitel((Titel)null);
        return;
      case MyDslPackage.USER_STORY__ROLLE:
        setRolle((Rolle)null);
        return;
      case MyDslPackage.USER_STORY__ZIEL:
        setZiel((Ziel)null);
        return;
      case MyDslPackage.USER_STORY__NUTZEN:
        setNutzen((Nutzen)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_STORY__TITEL:
        return titel != null;
      case MyDslPackage.USER_STORY__ROLLE:
        return rolle != null;
      case MyDslPackage.USER_STORY__ZIEL:
        return ziel != null;
      case MyDslPackage.USER_STORY__NUTZEN:
        return nutzen != null;
    }
    return super.eIsSet(featureID);
  }

} //UserStoryImpl
