/**
 * generated by Xtext 2.41.0.M1
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Ziel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ziel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl#getLchars <em>Lchars</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl#getSubjekt <em>Subjekt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl#getVerb <em>Verb</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ZielImpl extends MinimalEObjectImpl.Container implements Ziel
{
  /**
   * The default value of the '{@link #getLchars() <em>Lchars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLchars()
   * @generated
   * @ordered
   */
  protected static final String LCHARS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLchars() <em>Lchars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLchars()
   * @generated
   * @ordered
   */
  protected String lchars = LCHARS_EDEFAULT;

  /**
   * The default value of the '{@link #getSubjekt() <em>Subjekt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubjekt()
   * @generated
   * @ordered
   */
  protected static final String SUBJEKT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSubjekt() <em>Subjekt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubjekt()
   * @generated
   * @ordered
   */
  protected String subjekt = SUBJEKT_EDEFAULT;

  /**
   * The default value of the '{@link #getVerb() <em>Verb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerb()
   * @generated
   * @ordered
   */
  protected static final String VERB_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVerb() <em>Verb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerb()
   * @generated
   * @ordered
   */
  protected String verb = VERB_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ZielImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ZIEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLchars()
  {
    return lchars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLchars(String newLchars)
  {
    String oldLchars = lchars;
    lchars = newLchars;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ZIEL__LCHARS, oldLchars, lchars));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSubjekt()
  {
    return subjekt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubjekt(String newSubjekt)
  {
    String oldSubjekt = subjekt;
    subjekt = newSubjekt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ZIEL__SUBJEKT, oldSubjekt, subjekt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVerb()
  {
    return verb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerb(String newVerb)
  {
    String oldVerb = verb;
    verb = newVerb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ZIEL__VERB, oldVerb, verb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL__LCHARS:
        return getLchars();
      case MyDslPackage.ZIEL__SUBJEKT:
        return getSubjekt();
      case MyDslPackage.ZIEL__VERB:
        return getVerb();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL__LCHARS:
        setLchars((String)newValue);
        return;
      case MyDslPackage.ZIEL__SUBJEKT:
        setSubjekt((String)newValue);
        return;
      case MyDslPackage.ZIEL__VERB:
        setVerb((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL__LCHARS:
        setLchars(LCHARS_EDEFAULT);
        return;
      case MyDslPackage.ZIEL__SUBJEKT:
        setSubjekt(SUBJEKT_EDEFAULT);
        return;
      case MyDslPackage.ZIEL__VERB:
        setVerb(VERB_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL__LCHARS:
        return LCHARS_EDEFAULT == null ? lchars != null : !LCHARS_EDEFAULT.equals(lchars);
      case MyDslPackage.ZIEL__SUBJEKT:
        return SUBJEKT_EDEFAULT == null ? subjekt != null : !SUBJEKT_EDEFAULT.equals(subjekt);
      case MyDslPackage.ZIEL__VERB:
        return VERB_EDEFAULT == null ? verb != null : !VERB_EDEFAULT.equals(verb);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (lchars: ");
    result.append(lchars);
    result.append(", subjekt: ");
    result.append(subjekt);
    result.append(", verb: ");
    result.append(verb);
    result.append(')');
    return result.toString();
  }

} //ZielImpl
